//! {{project-name}} - IntentumDiff parser plugin.
//!
//! Language: {{language}}
//! Mode:     full-parse (plugin receives raw source and owns parsing)
//!
//! Steps to implement:
//!   1. Compile or implement your parser inside this Rust/Wasm crate.
//!   2. Implement `parse_source()` to emit a SemanticNode tree from raw source.
//!   3. Keep labels, spans, and structural hashes deterministic.
//!   4. Build: `cargo build --release --target wasm32-wasip2`
//!   5. Register in your Python package's pyproject.toml:
//!      [project.entry-points."intentumdiff.parsers"]
//!      {{language}} = "your_package:entry_point"

use intentdiff_plugin_sdk::tree::{SemanticNode, SemanticNodeBuilder};

const GRAMMAR_ID: &str = "{{language}}";
const LANGUAGE_IDS: &[&str] = &["{{language}}"];

fn line_end_col(line: &str) -> u32 {
    line.chars().count() as u32
}

fn is_interesting_line(line: &str) -> bool {
    let trimmed = line.trim();
    !trimmed.is_empty() && !trimmed.starts_with("//") && !trimmed.starts_with('#')
}

fn node_for_line(index: usize, line: &str) -> Option<SemanticNode> {
    if !is_interesting_line(line) {
        return None;
    }

    let line_no = (index + 1) as u32;
    let trimmed = line.trim();
    Some(
        SemanticNodeBuilder::new(
            format!("0.{index}"),
            "statement",
            trimmed,
            line_no,
            0,
            line_no,
            line_end_col(line),
            "",
        )
        .build(),
    )
}

fn parse_source(source: &str) -> SemanticNode {
    let children: Vec<SemanticNode> = source
        .lines()
        .enumerate()
        .filter_map(|(index, line)| node_for_line(index, line))
        .collect();

    let end_line = source.lines().count().max(1) as u32;
    SemanticNodeBuilder::new("0", "source_file", GRAMMAR_ID, 1, 0, end_line, 0, "")
        .children(children)
        .build()
}

fn process_impl(source: &str) -> String {
    serde_json::to_string(&parse_source(source))
        .unwrap_or_else(|error| format!(r#"{{"error":"serialization failed: {error}"}}"#))
}

// WIT exports are generated by wit-bindgen in real plugins. These functions
// show the shape expected by the IntentumDiff parser world.

pub fn get_parser_mode() -> &'static str {
    "full-parse"
}

pub fn grammar_id() -> &'static str {
    GRAMMAR_ID
}

pub fn language_ids() -> Vec<&'static str> {
    LANGUAGE_IDS.to_vec()
}

pub fn detect_language(filename: &str, _content: &str) -> String {
    if filename.ends_with(".{{language}}") {
        GRAMMAR_ID.to_string()
    } else {
        String::new()
    }
}

pub fn preprocess_source(source: &str) -> String {
    source.to_string()
}

pub fn process(input: &str, _language: &str, _filename: &str) -> String {
    process_impl(input)
}

pub fn trivia_node_types() -> Vec<&'static str> {
    Vec::new()
}
